// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhPOzqiayVraAG3Ur-66HEljV9Gmh71I',
    appId: '1:753787094896:web:aa977f36210c75aa36f1b5',
    messagingSenderId: '753787094896',
    projectId: 'expense-tracker-app-1e116',
    authDomain: 'expense-tracker-app-1e116.firebaseapp.com',
    storageBucket: 'expense-tracker-app-1e116.firebasestorage.app',
    measurementId: 'G-S7GH1QPRBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wEKD7OTUlQ85qp18Vcd3889KCmxruzI',
    appId: '1:753787094896:android:b7daf778954c4cb736f1b5',
    messagingSenderId: '753787094896',
    projectId: 'expense-tracker-app-1e116',
    storageBucket: 'expense-tracker-app-1e116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdmbMj6dvCFoGvtdC57-nD9dO7RFi6ANg',
    appId: '1:753787094896:ios:afd97c004aeeb8a336f1b5',
    messagingSenderId: '753787094896',
    projectId: 'expense-tracker-app-1e116',
    storageBucket: 'expense-tracker-app-1e116.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdmbMj6dvCFoGvtdC57-nD9dO7RFi6ANg',
    appId: '1:753787094896:ios:afd97c004aeeb8a336f1b5',
    messagingSenderId: '753787094896',
    projectId: 'expense-tracker-app-1e116',
    storageBucket: 'expense-tracker-app-1e116.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhPOzqiayVraAG3Ur-66HEljV9Gmh71I',
    appId: '1:753787094896:web:52d2b005215824a736f1b5',
    messagingSenderId: '753787094896',
    projectId: 'expense-tracker-app-1e116',
    authDomain: 'expense-tracker-app-1e116.firebaseapp.com',
    storageBucket: 'expense-tracker-app-1e116.firebasestorage.app',
    measurementId: 'G-2KNRG31BEB',
  );
}
